### ISSUE TITLE
registerCompletionItemProvider Example

### ISSUE THREAD

**Issue by musab** [pengx17/monaco-yaml#36]
Can we have an example using the registerCompletionItemProvider [example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) from Monaco playground? 

I've tried in many ways and unable to see the completion option expand. We found that: 
- If I change to a different language (ie. `plaintext`) the completion does popup. Only when I have the language set to `yaml` completion does not work.

I've created an example codesandbox here: https://codesandbox.io/s/silent-firefly-4rq4w?file=/index.jsx

If you change lines 72, and 92 from `yaml` to `plaintext` and type `l` anywhere in the editor you will see: 

![image](https://user-images.githubusercontent.com/34455928/98289634-75546800-1f76-11eb-87d6-01b4ba068540.png)

But having it set to `yaml` it does not work.

**Comment by yazaabed** [comment]
It is by design that we override the `registerCompletionItemProvider` by ours. The one that implemented is using the schema you provided to provide an auto completion. You can't override it. But if this is important for you I think we can provide a function that override the json-schema ones or merge them. 

You can check the implementation here: https://github.com/pengx17/monaco-yaml/blob/36e4f908e7248795754176e5eec709e7858345a2/src/yamlMode.ts#L32

**Comment by musab** [comment]
@yazaabed thank you for your response! 

> The one that implemented is using the schema you provided to provide an auto completion.

this option should be OK, are there any examples of how the schema should look/be shaped to support auto completion? Is there for example a `suggestions` key that needs to be added?

This is the schema we are currently using: https://json.schemastore.org/circleciconfig

**Comment by yazaabed** [comment]
You can use normal json-schema attributes, like enum will show you available list values. You can write normal json-schema for example:

Note `additionalProperties` will not allow to write wrong attributes. Also command/ctrl + space will show available properties.

```
schema: {
        $schema: "http://json-schema.org/draft-07/schema",
        type: "object",
        additionalProperties: false,
        properties: {
            kpis: {
                $ref: "#/definitions/kpis"
            },
            options: {
                type: "object"
            },
            data: {
                type: "object"
            }
        }
    }
```

**Comment by musab** [comment]
@yazaabed are we sure this is working correctly? I've tried the following schema

<details>
  <summary>json-schema:</summary>
  
  ```yaml
	{
	  "$schema": "http://json-schema.org/draft-07/schema#",
	  "title": "JSON Schema for Hadolint, a Dockerfile linter tool",
	  "description": "Dockerfile linter, validate inline bash, written in Haskell",
	  "type": "object",
	  "additionalProperties": false,
	  "properties": {
	    "ignored": {
	      "type": "array",
	      "description": "A list of rules to be ignored",
	      "items": {
	        "type": "string",
	        "oneOf": [
	          {
	            "const": "DL3000",
	            "description": "Use absolute WORKDIR.",
	          },
	          {
	            "const": "DL3001",
	            "description": "For some bash commands it makes no sense running them in a Docker container like ssh, vim, shutdown, service, ps, free, top, kill, mount, ifconfig.",
	          },
	          {
	            "const": "DL3002",
	            "description": "Last user should not be root."
	          },
	          {
	            "const": "DL3003",
	            "description": "Use WORKDIR to switch to a directory.",
	          },
	          {
	            "const": "DL3004",
	            "description": "Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root.",
	          },
	          {
	            "const": "DL3005",
	            "description": "Do not use apt-get upgrade or dist-upgrade.",
	          }
	        ],
	        "title": "Rule",
	      }
	    },
	    "trustedRegistries": {
	      "type": "array",
	      "description": "A list of trusted registries. Ex: docker.io",
	      "items": {
	        "type": "string"
	      }
	    }
	  }
	}
  ```
</details>

and I should be seeing the following behaviour: 
![jqgnscgmhbf6go2r7r5x](https://user-images.githubusercontent.com/34455928/98377043-51defb00-2012-11eb-82a8-64f04cce35e3.gif)

but I do not see a code completion option show up for me. 

Here's a code sandbox with the above YAML to see: https://codesandbox.io/s/musing-sky-sy4v4?file=/index.jsx
